### ISSUE TITLE
share-function

### ISSUE THREAD

**Issue by aberlin** [LukeStonehm/LogicalDefence#23] opened 2015-05-20 20:02 UTC
sometimes it would be useful to have the ability to share a logical fault in a chat. 

This could be a start for an Implementation:
http://stackoverflow.com/questions/5646104/how-to-implement-the-share-function-of-a-android-app#5646627

**Comment by LukeStonehm** [comment] 2015-05-21 07:03
Thank you for this, I am already working on a share function :smile: 

See the following issue
https://github.com/LukeStonehm/LogicalDefence/issues/20

I'm closing this issue as a duplicate of the above linked issue :+1:

**Closed by LukeStonehm** 2015-05-21 07:03 UTC
